services:
  got1:
    image: gotenberg/gotenberg:8
    command: >
      gotenberg --api-timeout=300s --api-body-limit=200MB
      --chromium-auto-start=true --chromium-start-timeout=60s
      --chromium-max-queue-size=200 --chromium-disable-javascript=true
    restart: unless-stopped
    networks:
      - gotenberg_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  got2:
    image: gotenberg/gotenberg:8
    command: >
      gotenberg --api-timeout=300s --api-body-limit=200MB
      --chromium-auto-start=true --chromium-start-timeout=60s
      --chromium-max-queue-size=200 --chromium-disable-javascript=true
    restart: unless-stopped
    networks:
      - gotenberg_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  got3:
    image: gotenberg/gotenberg:8
    command: >
      gotenberg --api-timeout=300s --api-body-limit=200MB
      --chromium-auto-start=true --chromium-start-timeout=60s
      --chromium-max-queue-size=200 --chromium-disable-javascript=true
    restart: unless-stopped
    networks:
      - gotenberg_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  got4:
    image: gotenberg/gotenberg:8
    command: >
      gotenberg --api-timeout=300s --api-body-limit=200MB
      --chromium-auto-start=true --chromium-start-timeout=60s
      --chromium-max-queue-size=200 --chromium-disable-javascript=true
    restart: unless-stopped
    networks:
      - gotenberg_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  got5:
    image: gotenberg/gotenberg:8
    command: >
      gotenberg --api-timeout=300s --api-body-limit=200MB
      --chromium-auto-start=true --chromium-start-timeout=60s
      --chromium-max-queue-size=200 --chromium-disable-javascript=true
    restart: unless-stopped
    networks:
      - gotenberg_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  got6:
    image: gotenberg/gotenberg:8
    command: >
      gotenberg --api-timeout=300s --api-body-limit=200MB
      --chromium-auto-start=true --chromium-start-timeout=60s
      --chromium-max-queue-size=200 --chromium-disable-javascript=true
    restart: unless-stopped
    networks:
      - gotenberg_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  got7:
    image: gotenberg/gotenberg:8
    command: >
      gotenberg --api-timeout=300s --api-body-limit=200MB
      --chromium-auto-start=true --chromium-start-timeout=60s
      --chromium-max-queue-size=200 --chromium-disable-javascript=true
    restart: unless-stopped
    networks:
      - gotenberg_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  got8:
    image: gotenberg/gotenberg:8
    command: >
      gotenberg --api-timeout=300s --api-body-limit=200MB
      --chromium-auto-start=true --chromium-start-timeout=60s
      --chromium-max-queue-size=200 --chromium-disable-javascript=true
    restart: unless-stopped
    networks:
      - gotenberg_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lb:
    image: nginx:alpine
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [got1, got2, got3, got4, got5, got6, got7, got8]
    restart: unless-stopped
    networks:
      - gotenberg_network

networks:
  gotenberg_network:
    driver: bridge
